Add MILA extensions
MILA-Wien/collectivo-mila pull request #40
Opened 2023-05-08 06:37 UTC by JoelForamitti

Adopt the structure of https://github.com/MILA-Wien/collectivo-quickstart

2023-06-20 09:36 UTC, nanu-c requested changes

2023-06-20 09:36 UTC, nanu-c commented on collectivo/extensions/mila/direktkredit/setup.py
> +    # TODO Warning if os environ var is missing
maybe solve this todo?

2023-06-20 09:36 UTC, nanu-c commented on docker/keycloak-dev/Dockerfile
> +FROM quay.io/keycloak/keycloak:19.0.2
The collectivo repo already uses 21.0.2

2023-06-22 07:08 UTC, JoelForamitti commented on collectivo/extensions/mila/direktkredit/setup.py
> +    # TODO Warning if os environ var is missing
done!

2023-06-22 07:08 UTC, JoelForamitti commented on docker/keycloak-dev/Dockerfile
> +FROM quay.io/keycloak/keycloak:19.0.2
changed!

2023-06-22 07:50 UTC, nanu-c approved these changes

2023-06-22 08:04 UTC, merged